// <auto-generated />
using System;
using Lms.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lms.Application.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260822195255_RemoveGeneralComplianceType")]
    partial class RemoveGeneralComplianceType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Lms.Domain.Entities.AssessmentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssessmentAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssessmentQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentQuestionId");

                    b.HasIndex("AssessmentAttemptId", "AssessmentQuestionId")
                        .IsUnique();

                    b.ToTable("AssessmentAnswers");
                });

            modelBuilder.Entity("Lms.Domain.Entities.AssessmentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CourseAssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExamProctoringSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackSummary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ScorePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamProctoringSessionId")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.HasIndex("CourseAssessmentId", "UserAccountId", "SubmittedAt");

                    b.ToTable("AssessmentAttempts");
                });

            modelBuilder.Entity("Lms.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseAssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseAssessmentId", "OrderIndex");

                    b.ToTable("AssessmentQuestions");
                });

            modelBuilder.Entity("Lms.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Lms.Domain.Entities.BrokerLearnerAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BrokerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearnerUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("LearnerUserId");

                    b.HasIndex("BrokerUserId", "LearnerUserId")
                        .IsUnique();

                    b.ToTable("BrokerLearnerAssignments");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CompletionCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationDirectorName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryCourseCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.HasIndex("VerificationCode")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "ExpiresAt");

                    b.ToTable("CompletionCertificates");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletionWindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComplianceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ContinuingEducationType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("DistanceEducation");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EnrollmentClosesAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumAttendancePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(80);

                    b.Property<int>("MinimumPassingPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(75);

                    b.Property<Guid?>("OwnerInstructorId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryCourseCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredInstructionalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("RequiresProctoredExam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerInstructorId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseActivitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "EndedAtUtc");

                    b.HasIndex("CourseId", "UserAccountId", "StartedAtUtc");

                    b.ToTable("CourseActivitySessions");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxRetakesPerLearner")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PassPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetakeCooldownMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "IsRequired");

                    b.ToTable("CourseAssessments");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseCheckpointDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GatesProgression")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("CourseId", "Key")
                        .IsUnique();

                    b.ToTable("CourseCheckpointDefinitions");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseCheckpointOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseCheckpointDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseCheckpointDefinitionId", "OrderIndex");

                    b.ToTable("CourseCheckpointOptions");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.HasIndex("EnrollmentId", "ReminderType")
                        .IsUnique();

                    b.ToTable("CourseReminders");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AccessGrantedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AssessmentReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CourseStartReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueSoonReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnrollmentClosingReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentSource")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OverdueReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SponsoredByBrokerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PaymentTransactionId");

                    b.HasIndex("DueAtUtc", "Completed");

                    b.HasIndex("SponsoredByBrokerUserId", "EnrollmentSource");

                    b.HasIndex("UserAccountId", "CourseId")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "DueAtUtc");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Lms.Domain.Entities.ExamProctoringSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClosedBookConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSessionId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IdentityVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProctorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityIncidentNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SecurityIncidentReported")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSessionId");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("CourseId", "UserAccountId", "ExpiresAtUtc");

                    b.ToTable("ExamProctoringSessions");
                });

            modelBuilder.Entity("Lms.Domain.Entities.InstructorPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeTransferId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorPayouts");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PaymentTransactionId", "IssuedAt");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Lms.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserAccountId", "LessonId")
                        .IsUnique();

                    b.ToTable("LessonProgresses");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Lms.Domain.Entities.ModuleCheckpointProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PassedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserAccountId", "CourseId", "CheckpointKey")
                        .IsUnique();

                    b.ToTable("ModuleCheckpointProgresses");
                });

            modelBuilder.Entity("Lms.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("LearnerId", "CreatedAt");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Lms.Domain.Entities.PolicyDisclosureAcknowledgment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnualSummaryReportData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DisclosurePublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisclosureTextSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisclosureVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectronicSignature")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstructionalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseExaminationPerformanceRecord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProctoringFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryCourseCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentLegalName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportTelephone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TuitionAndFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("PaymentTransactionId");

                    b.HasIndex("LearnerId", "CourseId", "AcknowledgedAtUtc");

                    b.ToTable("PolicyDisclosureAcknowledgments");
                });

            modelBuilder.Entity("Lms.Domain.Entities.PurchaseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PaymentTransactionId");

                    b.ToTable("PurchaseLines");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FraudFlaggedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FraudReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("FraudRiskLevel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFlaggedForReview")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeRefundId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTransactionId");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Lms.Domain.Entities.RetakeGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseAssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrantedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GrantedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByAdminId");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("CourseAssessmentId", "UserAccountId")
                        .IsUnique();

                    b.ToTable("RetakeGrants");
                });

            modelBuilder.Entity("Lms.Domain.Entities.SchoolProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdvertisedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnualSummaryReportData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorporateOfficerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationDirectorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorLicenseNumber")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseExaminationPerformanceRecord")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryInstructorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLicenseNumber")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportHours")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportTelephone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchoolProfiles");
                });

            modelBuilder.Entity("Lms.Domain.Entities.SchoolStaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SchoolProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchoolProfileId", "Role");

                    b.ToTable("SchoolStaffMembers");
                });

            modelBuilder.Entity("Lms.Domain.Entities.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPerCycle")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Lms.Domain.Entities.SystemNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "ReadAt", "CreatedAt");

                    b.ToTable("SystemNotifications");
                });

            modelBuilder.Entity("Lms.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InitialLicensureDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBicEligible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegalName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseStatus")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LockoutEndUtc");

                    b.HasIndex("PasswordExpiresAt");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Lms.Domain.Entities.AssessmentAnswer", b =>
                {
                    b.HasOne("Lms.Domain.Entities.AssessmentAttempt", "AssessmentAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("AssessmentAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.AssessmentQuestion", "AssessmentQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("AssessmentQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentAttempt");

                    b.Navigation("AssessmentQuestion");
                });

            modelBuilder.Entity("Lms.Domain.Entities.AssessmentAttempt", b =>
                {
                    b.HasOne("Lms.Domain.Entities.CourseAssessment", "CourseAssessment")
                        .WithMany("Attempts")
                        .HasForeignKey("CourseAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.ExamProctoringSession", "ExamProctoringSession")
                        .WithOne("AssessmentAttempt")
                        .HasForeignKey("Lms.Domain.Entities.AssessmentAttempt", "ExamProctoringSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lms.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("AssessmentAttempts")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAssessment");

                    b.Navigation("ExamProctoringSession");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Lms.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("Lms.Domain.Entities.CourseAssessment", "CourseAssessment")
                        .WithMany("Questions")
                        .HasForeignKey("CourseAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAssessment");
                });

            modelBuilder.Entity("Lms.Domain.Entities.BrokerLearnerAssignment", b =>
                {
                    b.HasOne("Lms.Domain.Entities.UserAccount", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lms.Domain.Entities.UserAccount", "BrokerUser")
                        .WithMany("BrokerAssignments")
                        .HasForeignKey("BrokerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "LearnerUser")
                        .WithMany("LearnerAssignments")
                        .HasForeignKey("LearnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("BrokerUser");

                    b.Navigation("LearnerUser");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CompletionCertificate", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany("CompletionCertificates")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.Enrollment", "Enrollment")
                        .WithOne("CompletionCertificate")
                        .HasForeignKey("Lms.Domain.Entities.CompletionCertificate", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("CompletionCertificates")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseActivitySession", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany("ActivitySessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("CourseActivitySessions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseAssessment", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany("Assessments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseCheckpointDefinition", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseCheckpointOption", b =>
                {
                    b.HasOne("Lms.Domain.Entities.CourseCheckpointDefinition", "CourseCheckpointDefinition")
                        .WithMany("Options")
                        .HasForeignKey("CourseCheckpointDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseCheckpointDefinition");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseReminder", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("Reminders")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.PaymentTransaction", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("PaymentTransactionId");

                    b.HasOne("Lms.Domain.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("SponsoredByBrokerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lms.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Lms.Domain.Entities.ExamProctoringSession", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany("ExamProctoringSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("ExamProctoringSessions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Lms.Domain.Entities.InstructorPayout", b =>
                {
                    b.HasOne("Lms.Domain.Entities.UserAccount", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Lms.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Lms.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Module", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Lms.Domain.Entities.ModuleCheckpointProgress", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany("ModuleCheckpointProgresses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("ModuleCheckpointProgresses")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Lms.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Lms.Domain.Entities.UserAccount", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Lms.Domain.Entities.PolicyDisclosureAcknowledgment", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lms.Domain.Entities.UserAccount", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany("PolicyDisclosureAcknowledgments")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Enrollment");

                    b.Navigation("Learner");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("Lms.Domain.Entities.PurchaseLine", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Refund", b =>
                {
                    b.HasOne("Lms.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("Lms.Domain.Entities.RetakeGrant", b =>
                {
                    b.HasOne("Lms.Domain.Entities.CourseAssessment", "CourseAssessment")
                        .WithMany()
                        .HasForeignKey("CourseAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "GrantedByAdmin")
                        .WithMany()
                        .HasForeignKey("GrantedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAssessment");

                    b.Navigation("GrantedByAdmin");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Lms.Domain.Entities.SchoolStaffMember", b =>
                {
                    b.HasOne("Lms.Domain.Entities.SchoolProfile", "SchoolProfile")
                        .WithMany("StaffMembers")
                        .HasForeignKey("SchoolProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolProfile");
                });

            modelBuilder.Entity("Lms.Domain.Entities.ShoppingCart", b =>
                {
                    b.OwnsMany("Lms.Domain.Entities.CartItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AddedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("CourseId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CourseTitle")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Price")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ShoppingCartId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ShoppingCartId");

                            b1.ToTable("CartItem");

                            b1.WithOwner()
                                .HasForeignKey("ShoppingCartId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Lms.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms.Domain.Entities.UserAccount", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Lms.Domain.Entities.SystemNotification", b =>
                {
                    b.HasOne("Lms.Domain.Entities.UserAccount", "RecipientUser")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Lms.Domain.Entities.AssessmentAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Lms.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Course", b =>
                {
                    b.Navigation("ActivitySessions");

                    b.Navigation("Assessments");

                    b.Navigation("CompletionCertificates");

                    b.Navigation("Enrollments");

                    b.Navigation("ExamProctoringSessions");

                    b.Navigation("ModuleCheckpointProgresses");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseAssessment", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Lms.Domain.Entities.CourseCheckpointDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("CompletionCertificate");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("Lms.Domain.Entities.ExamProctoringSession", b =>
                {
                    b.Navigation("AssessmentAttempt");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("LessonProgresses");
                });

            modelBuilder.Entity("Lms.Domain.Entities.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Lms.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Invoices");

                    b.Navigation("PolicyDisclosureAcknowledgments");

                    b.Navigation("PurchaseLines");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Lms.Domain.Entities.SchoolProfile", b =>
                {
                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("Lms.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("AssessmentAttempts");

                    b.Navigation("BrokerAssignments");

                    b.Navigation("CompletionCertificates");

                    b.Navigation("CourseActivitySessions");

                    b.Navigation("Enrollments");

                    b.Navigation("ExamProctoringSessions");

                    b.Navigation("LearnerAssignments");

                    b.Navigation("LessonProgresses");

                    b.Navigation("ModuleCheckpointProgresses");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
